server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 192.168.179.130
    port: 5672
    username: admin
    password: 123
  cloud:
    stream:
      binders:    # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:    # 表示定义的名称，用于binding整合. 自定义
          type: rabbit    # 消息组件类型
      bindings:   # 服务的整合处理
        input:    # 这个名字是一个通道的名称
          destination: studyExchange  # 表示要使用的Exchange名称，自定义
          content-type: application/json  # 设置消息类型, 本次为json; 文本可以设置为"text/plain"
          binder: defaultRabbit     # 设置要绑定的消息服务的具体设置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  # 设置心跳的时间间隔(默认30秒)
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8802.com    # 信息列表显示的主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址